import type { Dashboard, WidgetTemplate } from "./types";

const DAY = 24 * 60 * 60_000;
const HOUR = 60 * 60_000;

const VEDANTA = { name: "Vedanta Neogi", avatarColor: "#7c8a5b" };
const SYSTEM = { name: "Datadog", avatarColor: "#774aa4" };

export const MOCK_DASHBOARDS: Dashboard[] = [
  {
    id: "vedantas-fri-may-1",
    name: "Vedanta's Dashboard Fri, May 1, 3:27:30 pm",
    kind: "dashboard",
    author: VEDANTA,
    modifiedMs: Date.now() - 2 * HOUR,
    popularity: 5,
    teams: [],
  },
  {
    id: "email-delivery-tracking",
    name: "Email Delivery Tracking",
    kind: "dashboard",
    icon: "system",
    author: SYSTEM,
    modifiedMs: Date.now() - 7 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "containers-overview",
    name: "Containers - Overview",
    kind: "dashboard",
    icon: "container",
    author: SYSTEM,
    modifiedMs: Date.now() - 30 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "datadog-audit-trail-overview",
    name: "Datadog Audit Trail Overview",
    kind: "dashboard",
    icon: "system",
    author: SYSTEM,
    modifiedMs: Date.now() - 15 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "docker-overview",
    name: "Docker - Overview",
    kind: "screenboard",
    icon: "docker",
    author: SYSTEM,
    modifiedMs: Date.now() - 60 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "estimated-usage-overview",
    name: "Estimated Usage Overview",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 10 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "host-counts",
    name: "Host Counts",
    kind: "screenboard",
    icon: "system",
    author: SYSTEM,
    modifiedMs: Date.now() - 45 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "host-metrics-1",
    name: "Host Metrics",
    kind: "dashboard",
    icon: "system",
    author: SYSTEM,
    modifiedMs: Date.now() - 50 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "host-metrics-2",
    name: "Host Metrics",
    kind: "dashboard",
    icon: "system",
    author: SYSTEM,
    modifiedMs: Date.now() - 50 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "legacy-rum-errors",
    name: "[Legacy] RUM - Errors",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 90 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "legacy-rum-frustration-signals",
    name: "[Legacy] RUM - Frustration Signals",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 90 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "legacy-rum-mobile",
    name: "[Legacy] RUM - Mobile",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 90 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "legacy-rum-overview",
    name: "[Legacy] RUM - Overview",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 90 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "legacy-rum-performance-monitoring",
    name: "[Legacy] RUM - Performance Monitoring",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 90 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "log-management-overview",
    name: "Log Management - Overview",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 14 * DAY,
    popularity: 2,
    teams: [],
  },
  {
    id: "metrics-summary",
    name: "Metrics Summary",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 22 * DAY,
    popularity: 1,
    teams: [],
  },
  {
    id: "ntp-overview",
    name: "NTP - Overview",
    kind: "dashboard",
    icon: "system",
    author: SYSTEM,
    modifiedMs: Date.now() - 100 * DAY,
    popularity: 0,
    teams: [],
  },
  {
    id: "synthetics-summary",
    name: "Synthetics Summary",
    kind: "dashboard",
    icon: "datadog",
    author: SYSTEM,
    modifiedMs: Date.now() - 18 * DAY,
    popularity: 1,
    teams: [],
  },
];

export const WIDGET_TEMPLATES: WidgetTemplate[] = [
  { id: "timeseries", label: "Timeseries", category: "graph", widgetType: "timeseries" },
  { id: "query-value", label: "Query Value", category: "graph", widgetType: "query_value" },
  { id: "top-list", label: "Top List", category: "graph", widgetType: "top_list" },
  { id: "table", label: "Table", category: "graph", widgetType: "table" },
  { id: "list", label: "List", category: "graph" },
  { id: "pie-chart", label: "Pie Chart", category: "graph", widgetType: "pie-chart" },
  { id: "bar-chart", label: "Bar Chart", category: "graph" },
  { id: "treemap", label: "Treemap", category: "graph" },
  { id: "distribution", label: "Distribution", category: "graph", widgetType: "distribution" },
  { id: "heatmap", label: "Heatmap", category: "graph", widgetType: "heatmap" },
  { id: "geomap", label: "Geomap", category: "graph" },
  { id: "scatter-plot", label: "Scatter Plot", category: "graph" },
  { id: "service-summary", label: "Service Summary", category: "graph" },
  { id: "alert-graph", label: "Alert Graph", category: "graph" },
  { id: "alert-value", label: "Alert Value", category: "graph" },
  { id: "check-status", label: "Check Status", category: "graph" },
  { id: "change", label: "Change", category: "graph", widgetType: "change" },
  { id: "group", label: "Group", category: "group" },
  { id: "powerpack", label: "Powerpack", category: "group" },
  { id: "note", label: "Note", category: "annotation" },
  { id: "free-text", label: "Free Text", category: "annotation" },
  { id: "image", label: "Image", category: "annotation" },
  { id: "iframe", label: "iFrame", category: "annotation" },
];
