import type { WidgetTemplate } from "./types";

export const WIDGET_TEMPLATES: WidgetTemplate[] = [
  { id: "timeseries", label: "Timeseries", category: "graph", widgetType: "timeseries" },
  { id: "query-value", label: "Query Value", category: "graph", widgetType: "query_value" },
  { id: "top-list", label: "Top List", category: "graph", widgetType: "top_list" },
  { id: "table", label: "Table", category: "graph", widgetType: "table" },
  { id: "list", label: "List", category: "graph" },
  { id: "pie-chart", label: "Pie Chart", category: "graph", widgetType: "pie-chart" },
  { id: "bar-chart", label: "Bar Chart", category: "graph" },
  { id: "treemap", label: "Treemap", category: "graph" },
  { id: "distribution", label: "Distribution", category: "graph", widgetType: "distribution" },
  { id: "heatmap", label: "Heatmap", category: "graph", widgetType: "heatmap" },
  { id: "geomap", label: "Geomap", category: "graph" },
  { id: "scatter-plot", label: "Scatter Plot", category: "graph" },
  { id: "service-summary", label: "Service Summary", category: "graph" },
  { id: "alert-graph", label: "Alert Graph", category: "graph" },
  { id: "alert-value", label: "Alert Value", category: "graph" },
  { id: "check-status", label: "Check Status", category: "graph" },
  { id: "change", label: "Change", category: "graph", widgetType: "change" },
  { id: "group", label: "Group", category: "group" },
  { id: "powerpack", label: "Powerpack", category: "group" },
  { id: "note", label: "Note", category: "annotation" },
  { id: "free-text", label: "Free Text", category: "annotation" },
  { id: "image", label: "Image", category: "annotation" },
  { id: "iframe", label: "iFrame", category: "annotation" },
];
