import type {
  ApmRecommendation,
  ApmResource,
  ApmService,
  ApmServiceSeries,
  ApmSpan,
} from "./types";

export const APM_SERVICES: ApmService[] = [
  {
    id: "postgres",
    name: "postgres",
    type: "db",
    language: "python",
    env: "prod",
    health: "ok",
    requestsPerSec: 0.05,
    errorRate: null,
    p99LatencyMs: 276,
    p95LatencyMs: 264,
    totalRequests: 109,
    totalErrors: 0,
    lastDeployMinutesAgo: null,
  },
  {
    id: "auth",
    name: "auth",
    type: "web",
    language: "node",
    env: "prod",
    health: "ok",
    requestsPerSec: 0.08,
    errorRate: null,
    p99LatencyMs: 1360,
    p95LatencyMs: 1100,
    totalRequests: 138,
    totalErrors: 0,
    lastDeployMinutesAgo: 10,
  },
  {
    id: "redis",
    name: "redis",
    type: "cache",
    language: "node",
    env: "prod",
    health: "ok",
    requestsPerSec: 0.03,
    errorRate: null,
    p99LatencyMs: 173,
    p95LatencyMs: 151,
    totalRequests: 19,
    totalErrors: 0,
    lastDeployMinutesAgo: null,
  },
  {
    id: "api",
    name: "api",
    type: "web",
    language: "python",
    env: "prod",
    health: "ok",
    requestsPerSec: 0.06,
    errorRate: null,
    p99LatencyMs: 1050,
    p95LatencyMs: 880,
    totalRequests: 34,
    totalErrors: 0,
    lastDeployMinutesAgo: null,
  },
  {
    id: "worker",
    name: "worker",
    type: "custom",
    language: "node",
    env: "prod",
    health: "warn",
    requestsPerSec: 0.01,
    errorRate: 0.4,
    p99LatencyMs: 18,
    p95LatencyMs: 14,
    totalRequests: 10,
    totalErrors: 4,
    lastDeployMinutesAgo: null,
  },
];

export const APM_RECOMMENDATIONS: ApmRecommendation[] = [];

const RESOURCES_BY_SERVICE: Record<string, ApmResource[]> = {
  postgres: [
    {
      id: "postgres.connect",
      name: "postgres.connect",
      service: "postgres",
      requests: 6,
      totalTimeMs: 1480,
      p95LatencyMs: 264,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "select-jobdiva-jobs-1",
      name: "SELECT jobdiva_jobs.id, …",
      service: "postgres",
      requests: 1,
      totalTimeMs: 825,
      p95LatencyMs: 825,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "begin",
      name: "BEGIN",
      service: "postgres",
      requests: 16,
      totalTimeMs: 424,
      p95LatencyMs: 32,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "rollback",
      name: "ROLLBACK",
      service: "postgres",
      requests: 16,
      totalTimeMs: 411,
      p95LatencyMs: 28.6,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "select-candidates",
      name: "SELECT jobdiva_candidates.id…",
      service: "postgres",
      requests: 2,
      totalTimeMs: 298,
      p95LatencyMs: 23.9,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "postgres.connection.rollback",
      name: "postgres.connection.rollback",
      service: "postgres",
      requests: null,
      totalTimeMs: 238,
      p95LatencyMs: 23.8,
      errors: null,
      errorRate: 0,
    },
    {
      id: "select-jobdiva-jobs-2",
      name: "SELECT jobdiva_jobs.id, …",
      service: "postgres",
      requests: 1,
      totalTimeMs: 170,
      p95LatencyMs: 170,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "select-users-permissions",
      name: "SELECT users_1.user_id, permissions.id, …",
      service: "postgres",
      requests: 4,
      totalTimeMs: 135,
      p95LatencyMs: 28,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "select-user-permissions",
      name: "SELECT user_permissions.user_id, …",
      service: "postgres",
      requests: 4,
      totalTimeMs: 122,
      p95LatencyMs: 26,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "select-users-by-id",
      name: "SELECT users.user_id, users.first_name, …",
      service: "postgres",
      requests: 2,
      totalTimeMs: 56,
      p95LatencyMs: 32,
      errors: 0,
      errorRate: 0,
    },
  ],
  "auth": [
    {
      id: "get-api-proxy",
      name: "GET /api/proxy/[...path]",
      service: "auth",
      requests: 20,
      totalTimeMs: 9800,
      p95LatencyMs: 502,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "get-slotting",
      name: "GET /slotting",
      service: "auth",
      requests: 14,
      totalTimeMs: 480,
      p95LatencyMs: 32.4,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "get-recruiting-jobs",
      name: "GET /recruiting/jobs",
      service: "auth",
      requests: 12,
      totalTimeMs: 122,
      p95LatencyMs: 10.3,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "get-admin-index",
      name: "GET /admin/(index)",
      service: "auth",
      requests: 10,
      totalTimeMs: 415,
      p95LatencyMs: 39.5,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "post-workspace-selector",
      name: "POST /workspace-selector",
      service: "auth",
      requests: 18,
      totalTimeMs: 410,
      p95LatencyMs: 22.2,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "get-reporting",
      name: "GET /reporting",
      service: "auth",
      requests: 12,
      totalTimeMs: 388,
      p95LatencyMs: 32.8,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "get-scorecard-index",
      name: "GET /scorecard/(index)",
      service: "auth",
      requests: 10,
      totalTimeMs: 268,
      p95LatencyMs: 26.6,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "get-workspace-selector",
      name: "GET /workspace-selector",
      service: "auth",
      requests: 8,
      totalTimeMs: 412,
      p95LatencyMs: 51.4,
      errors: 0,
      errorRate: 0,
    },
  ],
  redis: [
    {
      id: "redis.setex",
      name: "SETEX",
      service: "redis",
      requests: 8,
      totalTimeMs: 3.16,
      p95LatencyMs: 0.4,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "redis.get",
      name: "GET",
      service: "redis",
      requests: 11,
      totalTimeMs: 2.2,
      p95LatencyMs: 0.3,
      errors: 0,
      errorRate: 0,
    },
  ],
  api: [
    {
      id: "fastapi.serialize_response",
      name: "fastapi.serialize_response",
      service: "api",
      requests: 17,
      totalTimeMs: 12.3,
      p95LatencyMs: 0.9,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "get-api-users",
      name: "GET /api/users",
      service: "api",
      requests: 8,
      totalTimeMs: 3760,
      p95LatencyMs: 471,
      errors: 0,
      errorRate: 0,
    },
    {
      id: "get-api-workspaces",
      name: "GET /api/workspaces",
      service: "api",
      requests: 9,
      totalTimeMs: 850,
      p95LatencyMs: 110,
      errors: 0,
      errorRate: 0,
    },
  ],
  worker: [
    {
      id: "node.handler",
      name: "node.handler",
      service: "worker",
      requests: 10,
      totalTimeMs: 180,
      p95LatencyMs: 18,
      errors: 4,
      errorRate: 0.4,
    },
  ],
};

export function getResourcesForService(serviceId: string): ApmResource[] {
  return RESOURCES_BY_SERVICE[serviceId] ?? [];
}

const NOW = Date.now();

function makeSeries(
  service: string,
  baseHits: number,
  errorRate = 0,
  baseLatency = 50,
): ApmServiceSeries {
  const points = Array.from({ length: 24 }, (_, i) => {
    const t = NOW - (24 - i) * 150_000;
    const factor = 0.5 + 0.5 * Math.sin((i + service.length) * 0.6);
    const hits = Math.max(0, Math.round(baseHits * factor * (i > 19 ? 2.4 : 0.05)));
    return {
      t,
      hits,
      errors: Math.round(hits * errorRate),
      latencyMs: baseLatency + Math.round(40 * factor),
    };
  });
  return { service, points };
}

export function getServiceSummarySeries(serviceId: string): ApmServiceSeries[] {
  const svc = APM_SERVICES.find((s) => s.id === serviceId);
  if (!svc) return [];
  const baseHits = svc.totalRequests;
  return [
    makeSeries(serviceId, baseHits, svc.errorRate ?? 0, svc.p95LatencyMs / 4),
  ];
}

export function getServiceResourceSeries(serviceId: string): ApmServiceSeries[] {
  const resources = getResourcesForService(serviceId).slice(0, 5);
  return resources.map((r, i) =>
    makeSeries(r.id, r.requests ?? 4, r.errorRate, r.p95LatencyMs / 6 + i * 4),
  );
}

const SAMPLE_SPAN_TEMPLATES: Array<Omit<ApmSpan, "id" | "timestampMs">> = [
  {
    service: "auth",
    resource: "POST /workspace-selector",
    durationMs: 14.3,
    method: "POST",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "POST /workspace-selector",
    durationMs: 22.2,
    method: "POST",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /slotting",
    durationMs: 16.2,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /slotting",
    durationMs: 32.4,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /recruiting/jobs",
    durationMs: 3.85,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /recruiting/jobs",
    durationMs: 10.3,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /admin/(index)",
    durationMs: 23.2,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /admin/(index)",
    durationMs: 39.5,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /reporting",
    durationMs: 17.8,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /reporting",
    durationMs: 32.8,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /scorecard/(index)",
    durationMs: 15.3,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /scorecard/(index)",
    durationMs: 26.6,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /workspace-selector",
    durationMs: 42.3,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /workspace-selector",
    durationMs: 51.4,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "postgres",
    resource: "ROLLBACK",
    durationMs: 23.6,
    method: null,
    statusCode: null,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /api/proxy/[...path]",
    durationMs: 496,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET /api/proxy/[...path]",
    durationMs: 502,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "auth",
    resource: "GET",
    durationMs: 487,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "api",
    resource: "GET /api/users",
    durationMs: 471,
    method: "GET",
    statusCode: 200,
    status: "ok",
  },
  {
    service: "api",
    resource: "fastapi.serialize_response",
    durationMs: 0.607,
    method: null,
    statusCode: null,
    status: "ok",
  },
  {
    service: "redis",
    resource: "SETEX",
    durationMs: 0.395,
    method: null,
    statusCode: null,
    status: "ok",
  },
  {
    service: "postgres",
    resource: "SELECT users_1.user_id, permissions.id, permissi…",
    durationMs: 26.3,
    method: null,
    statusCode: null,
    status: "ok",
  },
  {
    service: "postgres",
    resource: "SELECT user_permissions.user_id, user_permissi…",
    durationMs: 25.2,
    method: null,
    statusCode: null,
    status: "ok",
  },
  {
    service: "postgres",
    resource: "SELECT users.user_id, users.first_name, users.las…",
    durationMs: 23.2,
    method: null,
    statusCode: null,
    status: "ok",
  },
  {
    service: "worker",
    resource: "node.handler",
    durationMs: 18.0,
    method: null,
    statusCode: 500,
    status: "error",
  },
];

export const APM_SPANS: ApmSpan[] = (() => {
  const spans: ApmSpan[] = [];
  let id = 0;
  const baseTime = NOW - 60_000;
  for (let cycle = 0; cycle < 13; cycle += 1) {
    SAMPLE_SPAN_TEMPLATES.forEach((tpl, i) => {
      id += 1;
      spans.push({
        id: `span_${id}`,
        timestampMs: baseTime + cycle * 8_000 + i * 60,
        ...tpl,
      });
    });
  }
  return spans.sort((a, b) => b.timestampMs - a.timestampMs);
})();
