import type { Monitor, MonitorTypeOption } from "./types";

const HOUR = 60 * 60_000;
const DAY = 24 * HOUR;

const VEDANTA = { name: "Vedanta Neogi", avatarColor: "#7c8a5b" };

export const MOCK_MONITORS: Monitor[] = [
  {
    id: "anr-rate-is-high",
    name: "ANR Rate is high",
    status: "OK",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query:
      "sum(last_1h):(sum:rum.measure.error.anr{*}.as_count() / sum:rum.measure.session{*}.as_count()) * 100 > 0.47",
    evaluationLabel: "SUM over the last 1h",
    thresholdLabel: "y > 0.47",
    threshold: 0.47,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "The ANR (Application Not Responding) rate for $application.name has reached {{value}}% — exceeding the critical threshold of {{threshold}}% — over the last hour.",
    recoveryMessage:
      "ANR rate for $application.name has recovered. Current value: {{value}}%.",
    impact:
      "ANRs are highly visible and disruptive — users are presented with a system dialog prompting them to kill the app. High ANR rates lead to poor Play Store ratings, increased force-close rates, and user churn.",
    runbookSteps: [
      "Open RUM Error Tracking and filter by application.name:$application.name and error type anr.",
      "Identify the most common ANR stack traces and the activities/services where they occur.",
      "Check if the ANR rate spike correlates with a recent app release in the RUM Explorer.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "app-startup-time-is-high",
    name: "App Startup Time is high",
    status: "No Data",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query: "avg(last_15m):avg:rum.measure.app_startup{*} > 3000",
    evaluationLabel: "AVG over the last 15m",
    thresholdLabel: "y > 3000",
    threshold: 3000,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "App Startup Time for $application.name has reached {{value}}ms — exceeding the threshold of {{threshold}}ms.",
    recoveryMessage:
      "App startup time for $application.name has recovered. Current value: {{value}}ms.",
    impact:
      "Slow startup is one of the strongest predictors of session abandonment. Users frequently churn during cold starts that exceed 3 seconds.",
    runbookSteps: [
      "Open the RUM Mobile dashboard and filter by application.name:$application.name.",
      "Inspect cold-start traces in the Mobile Performance view.",
      "Check whether the regression aligns with a recent release.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "crash-free-session-rate-is-low",
    name: "Crash-Free Session Rate is low",
    status: "OK",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query: "avg(last_1h):avg:rum.measure.crash_free_rate{*} < 99",
    evaluationLabel: "AVG over the last 1h",
    thresholdLabel: "y < 99",
    threshold: 99,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "Crash-Free Session Rate for $application.name has dropped to {{value}}% — below the threshold of {{threshold}}%.",
    recoveryMessage:
      "Crash-Free Session Rate for $application.name has recovered. Current value: {{value}}%.",
    impact:
      "A drop in crash-free sessions correlates strongly with negative Play Store / App Store ratings and user churn.",
    runbookSteps: [
      "Open RUM Error Tracking and filter by application.name:$application.name and error type crash.",
      "Identify the top crash stack traces and the affected app version.",
      "Roll back or hotfix if a single release accounts for the regression.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "cumulative-layout-shift-is-high",
    name: "Cumulative Layout Shift is high for view {{[view.name].name}}",
    status: "OK",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query: "avg(last_1h):avg:rum.measure.cls{*} by {view.name} > 0.25",
    evaluationLabel: "AVG over the last 1h",
    thresholdLabel: "y > 0.25",
    threshold: 0.25,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "Cumulative Layout Shift for view {{view.name}} has reached {{value}} — exceeding the threshold of {{threshold}}.",
    recoveryMessage:
      "CLS for view {{view.name}} has recovered. Current value: {{value}}.",
    impact:
      "High CLS makes the page feel unstable and disrupts task flow. Google Web Vitals classifies CLS > 0.25 as 'Poor', impacting SEO ranking.",
    runbookSteps: [
      "Open RUM Performance and filter by view.name:{{view.name}}.",
      "Identify the largest layout-shifting elements via Core Web Vitals breakdown.",
      "Reserve space for late-loading images, ads, and embeds.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "hang-rate-is-high",
    name: "Hang Rate is high",
    status: "OK",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query: "sum(last_1h):sum:rum.measure.hang{*}.as_count() > 50",
    evaluationLabel: "SUM over the last 1h",
    thresholdLabel: "y > 50",
    threshold: 50,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message: "Hang Rate has reached {{value}} — exceeding {{threshold}}.",
    recoveryMessage: "Hang Rate has recovered. Current value: {{value}}.",
    impact:
      "App hangs leave users staring at a frozen UI, often leading to forced kills and one-star reviews.",
    runbookSteps: [
      "Open RUM Mobile and filter by application.name:$application.name.",
      "Inspect the Hang Rate breakdown by activity / view.",
      "Profile the most impacted views to find blocking work on the main thread.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "interaction-to-next-paint-is-high",
    name: "Interaction to Next Paint is high for view {{[view.name].name}}",
    status: "OK",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query: "avg(last_1h):avg:rum.measure.inp{*} by {view.name} > 500",
    evaluationLabel: "AVG over the last 1h",
    thresholdLabel: "y > 500",
    threshold: 500,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "INP for view {{view.name}} has reached {{value}}ms — exceeding {{threshold}}ms.",
    recoveryMessage:
      "INP for view {{view.name}} has recovered. Current value: {{value}}ms.",
    impact:
      "INP > 500ms is classified as 'Poor' by Google. Users perceive the app as sluggish and unresponsive.",
    runbookSteps: [
      "Open RUM Performance and filter by view.name:{{view.name}}.",
      "Inspect the Interaction breakdown to find the slowest event handlers.",
      "Move heavy work off the main thread or split into smaller tasks.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "largest-contentful-paint-is-high",
    name: "Largest Contentful Paint is high for view {{[view.name].name}}",
    status: "OK",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query: "avg(last_1h):avg:rum.measure.lcp{*} by {view.name} > 2500",
    evaluationLabel: "AVG over the last 1h",
    thresholdLabel: "y > 2500",
    threshold: 2500,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "LCP for view {{view.name}} has reached {{value}}ms — exceeding {{threshold}}ms.",
    recoveryMessage:
      "LCP for view {{view.name}} has recovered. Current value: {{value}}ms.",
    impact:
      "Slow LCP delays the user's perception of meaningful content and contributes to bounce rate.",
    runbookSteps: [
      "Open RUM Performance and filter by view.name:{{view.name}}.",
      "Identify the largest contentful element via the Web Vitals breakdown.",
      "Optimize hero images and reduce render-blocking resources.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "view-error-rate-is-high",
    name: "View Error Rate is high for view {{[view.name].name}}",
    status: "OK",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query:
      "sum(last_1h):(sum:rum.measure.error{*} by {view.name}.as_count() / sum:rum.measure.view{*} by {view.name}.as_count()) * 100 > 5",
    evaluationLabel: "SUM over the last 1h",
    thresholdLabel: "y > 5",
    threshold: 5,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "Error rate for view {{view.name}} has reached {{value}}% — exceeding {{threshold}}%.",
    recoveryMessage:
      "Error rate for view {{view.name}} has recovered. Current value: {{value}}%.",
    impact:
      "A spike in errors on a high-traffic view directly impacts conversion and user trust.",
    runbookSteps: [
      "Open RUM Error Tracking and filter by view.name:{{view.name}}.",
      "Group by error.message to find the top offenders.",
      "Correlate against recent deploys and feature flag rollouts.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "view-loading-time-is-high",
    name: "View Loading Time is high for view {{[view.name].name}}",
    status: "OK",
    priority: null,
    type: "rum",
    pack: "rum",
    tags: ["monitor_pack:rum"],
    query: "avg(last_1h):avg:rum.measure.loading_time{*} by {view.name} > 4000",
    evaluationLabel: "AVG over the last 1h",
    thresholdLabel: "y > 4000",
    threshold: 4000,
    source: "Real User Monitoring",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "Loading time for view {{view.name}} has reached {{value}}ms — exceeding {{threshold}}ms.",
    recoveryMessage:
      "Loading time for view {{view.name}} has recovered. Current value: {{value}}ms.",
    impact:
      "Slow page loads reduce engagement and increase bounce rate, especially on mobile networks.",
    runbookSteps: [
      "Open RUM Performance and filter by view.name:{{view.name}}.",
      "Inspect resource waterfalls for slow XHR / fetch calls.",
      "Defer non-critical work and lazy-load below-the-fold content.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "host-cpu-is-high",
    name: "Host CPU usage is high",
    status: "OK",
    priority: null,
    type: "host",
    pack: "host",
    tags: ["monitor_pack:host"],
    query: "avg(last_5m):avg:system.cpu.user{*} by {host} > 90",
    evaluationLabel: "AVG over the last 5m",
    thresholdLabel: "y > 90",
    threshold: 90,
    source: "Infrastructure",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "CPU usage on {{host.name}} has reached {{value}}% — exceeding {{threshold}}%.",
    recoveryMessage:
      "CPU usage on {{host.name}} has recovered. Current value: {{value}}%.",
    impact:
      "Sustained high CPU degrades service latency and can lead to cascading failures across the cluster.",
    runbookSteps: [
      "Open the Host Map and locate {{host.name}}.",
      "Inspect the top processes by CPU in the Live Processes view.",
      "Correlate against recent deploys or workload changes.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "host-memory-is-high",
    name: "Host Memory usage is high",
    status: "OK",
    priority: null,
    type: "host",
    pack: "host",
    tags: ["monitor_pack:host"],
    query: "avg(last_5m):avg:system.mem.used{*} by {host} > 90",
    evaluationLabel: "AVG over the last 5m",
    thresholdLabel: "y > 90",
    threshold: 90,
    source: "Infrastructure",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "Memory usage on {{host.name}} has reached {{value}}% — exceeding {{threshold}}%.",
    recoveryMessage:
      "Memory usage on {{host.name}} has recovered. Current value: {{value}}%.",
    impact:
      "Memory pressure causes OOM kills, increased GC pauses, and degraded throughput.",
    runbookSteps: [
      "Open the Host Map and locate {{host.name}}.",
      "Inspect the top processes by RSS in Live Processes.",
      "Investigate possible memory leaks in recently deployed services.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "host-disk-is-high",
    name: "Host Disk usage is high",
    status: "OK",
    priority: null,
    type: "host",
    pack: "host",
    tags: ["monitor_pack:host"],
    query: "avg(last_5m):avg:system.disk.in_use{*} by {host,device} > 0.85",
    evaluationLabel: "AVG over the last 5m",
    thresholdLabel: "y > 0.85",
    threshold: 0.85,
    source: "Infrastructure",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "Disk usage on {{host.name}} ({{device.name}}) has reached {{value}} — exceeding {{threshold}}.",
    recoveryMessage:
      "Disk usage on {{host.name}} ({{device.name}}) has recovered. Current value: {{value}}.",
    impact:
      "Hosts that hit disk capacity stop accepting writes, causing widespread service failures.",
    runbookSteps: [
      "Open the Host Map and locate {{host.name}}.",
      "Inspect the disk-usage breakdown in the Host Info panel.",
      "Truncate / archive logs and rotate large files.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "host-iowait-is-high",
    name: "Host IOWait is high",
    status: "OK",
    priority: null,
    type: "host",
    pack: "host",
    tags: ["monitor_pack:host"],
    query: "avg(last_5m):avg:system.cpu.iowait{*} by {host} > 30",
    evaluationLabel: "AVG over the last 5m",
    thresholdLabel: "y > 30",
    threshold: 30,
    source: "Infrastructure",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message: "IOWait on {{host.name}} has reached {{value}}%.",
    recoveryMessage: "IOWait on {{host.name}} has recovered. Current value: {{value}}%.",
    impact:
      "Sustained high IOWait indicates a saturated disk subsystem, slowing every workload on the host.",
    runbookSteps: [
      "Open the Host Map and locate {{host.name}}.",
      "Inspect the IO breakdown in the Host Info panel.",
      "Identify noisy-neighbor processes or move the workload off the host.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "host-load-is-high",
    name: "Host Load 15 is high",
    status: "OK",
    priority: null,
    type: "host",
    pack: "host",
    tags: ["monitor_pack:host"],
    query: "avg(last_5m):avg:system.load.15{*} by {host} > 4",
    evaluationLabel: "AVG over the last 5m",
    thresholdLabel: "y > 4",
    threshold: 4,
    source: "Infrastructure",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message: "Load 15 on {{host.name}} has reached {{value}}.",
    recoveryMessage: "Load 15 on {{host.name}} has recovered. Current value: {{value}}.",
    impact:
      "High load average is an early indicator of CPU contention and queueing across services.",
    runbookSteps: [
      "Open the Host Map and locate {{host.name}}.",
      "Inspect the top processes in Live Processes.",
      "Compare with recent deploys to find new workloads.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "host-not-reporting",
    name: "Host has stopped reporting",
    status: "OK",
    priority: null,
    type: "host",
    pack: "host",
    tags: ["monitor_pack:host"],
    query: "avg(last_5m):avg:datadog.agent.up{*} by {host} < 1",
    evaluationLabel: "AVG over the last 5m",
    thresholdLabel: "y < 1",
    threshold: 1,
    source: "Infrastructure",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message:
      "Host {{host.name}} has stopped reporting metrics for the last 5 minutes.",
    recoveryMessage: "Host {{host.name}} has resumed reporting metrics.",
    impact:
      "A silent host can mask outages — ensure the host is reachable and the agent is healthy.",
    runbookSteps: [
      "Confirm the host is up via the cloud provider console.",
      "Check the Datadog Agent status (`datadog-agent status`).",
      "Inspect agent logs for connectivity or auth issues.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
  {
    id: "host-ntp-offset",
    name: "Host clock is drifting (NTP offset high)",
    status: "OK",
    priority: null,
    type: "host",
    pack: "host",
    tags: ["monitor_pack:host"],
    query: "avg(last_5m):avg:ntp.offset{*} by {host} > 1",
    evaluationLabel: "AVG over the last 5m",
    thresholdLabel: "y > 1",
    threshold: 1,
    source: "Infrastructure",
    createdMs: Date.now() - 1 * DAY,
    author: VEDANTA,
    message: "NTP offset on {{host.name}} has reached {{value}}s.",
    recoveryMessage:
      "NTP offset on {{host.name}} has recovered. Current value: {{value}}s.",
    impact:
      "Clock drift produces misleading timestamps in logs and traces and can break TLS / token validation.",
    runbookSteps: [
      "SSH into {{host.name}} and confirm the NTP daemon is running.",
      "Run `chronyc tracking` or `ntpq -p` to inspect peer status.",
      "Restart the time daemon if peers are unreachable.",
    ],
    team: "support-techbrig-baeuv29da9go",
    muted: false,
  },
];

export const MONITOR_TYPE_OPTIONS: MonitorTypeOption[] = [
  {
    id: "metric",
    label: "Metric",
    description:
      "On each alert evaluation Datadog will calculate the average/minimum/maximum/sum over the selected period and check if it is above/below the threshold. This is the standard alert case where you know what sorts of values are unexpected.",
    configureLabel: "Configure Metric Monitor",
  },
  {
    id: "change",
    label: "Change",
    description:
      "Detect when a metric changes by a percentage or absolute value, compared to a previous time period.",
    configureLabel: "Configure Change Monitor",
  },
  {
    id: "anomaly",
    label: "Anomaly",
    description:
      "Use machine learning to detect when a metric behaves outside of its expected range.",
    configureLabel: "Configure Anomaly Monitor",
  },
  {
    id: "outlier",
    label: "Outlier",
    description:
      "Identify members of a group that behave differently from the rest of the group.",
    configureLabel: "Configure Outlier Monitor",
  },
  {
    id: "forecast",
    label: "Forecast",
    description:
      "Predict the future values of a metric and alert before it crosses a threshold.",
    configureLabel: "Configure Forecast Monitor",
  },
  {
    id: "host",
    label: "Host",
    description: "Alert when a host stops reporting to Datadog.",
    configureLabel: "Configure Host Monitor",
  },
  {
    id: "audit-trail",
    label: "Audit Trail",
    description: "Alert on Datadog Audit Trail events that match a query.",
    configureLabel: "Configure Audit Trail Monitor",
  },
  {
    id: "ci-tests",
    label: "CI & Tests",
    description: "Alert on continuous integration test failures and regressions.",
    configureLabel: "Configure CI Monitor",
  },
  {
    id: "composite",
    label: "Composite",
    description:
      "Combine multiple monitors into a single alert using a logical expression.",
    configureLabel: "Configure Composite Monitor",
  },
  {
    id: "data-observability",
    label: "Data Observability",
    description: "Alert on data quality issues across pipelines and datasets.",
    configureLabel: "Configure Data Observability Monitor",
  },
  {
    id: "error-tracking",
    label: "Error Tracking",
    description: "Alert when a new or regressing issue is detected.",
    configureLabel: "Configure Error Tracking Monitor",
  },
  {
    id: "event",
    label: "Event",
    description: "Alert when matching events occur in the Event Stream.",
    configureLabel: "Configure Event Monitor",
  },
  {
    id: "integration",
    label: "Integration",
    description: "Alert on the health and status of an installed integration.",
    configureLabel: "Configure Integration Monitor",
  },
  {
    id: "live-process",
    label: "Live Process",
    description: "Alert when a process count crosses a threshold.",
    configureLabel: "Configure Live Process Monitor",
  },
  {
    id: "llm-observability",
    label: "LLM Observability",
    description: "Alert on LLM application quality, latency, and cost regressions.",
    configureLabel: "Configure LLM Observability Monitor",
  },
];
